[package]
name = "smallpaint"
version = "0.1.0"
authors = ["Nathan Glenn <garfieldnate@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
rayon = "1.1"
thread_local = "1.1.4"
clap = "2.33.0"
